name: Build Test
on: [push, pull_request]

jobs:
  build:
    name: Build with Java 8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"
          cache: "maven"
      - run: java -version
      - run: mvn --version
      - run: mvn -B package
